# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://cangdow.github.io
date_format: "ordinal"
title: 罗杰的瓦尔登
subtitle: "发现未知的世界:人类被赋予了一种工作，那就是精神的成长。"
description: "罗杰的个人博客"
keywords: cangdow
favicon: /favicon.ico
timezone: Asia/Hangzhou
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: cangdow
organization: cangdow.
organization_url: cangdow
location: Hangzhou, China
email: dphe@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: cangdow.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: cangdow
douban_username: cangdow
facebook_username: cangdow
weibo_username: cangdow
zhihu_username: cangdow
twitter_username: cangdow

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: cangdow
disqus_username: cangdow
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, C++, Python, Design Patterns]
skill_mobile_app_keywords: [Android, Reverse Engineering]
skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
